### ISSUE TITLE
Stuck on "Error occurred during initialization of [Java] VM"

### ISSUE THREAD

**Issue by MincingWords** [JGCRI/gcam-core#309]
Have successfully built GCAM 7.0 on Gentoo Linux. JDK is openjdk-bin-17. 

When I run ./gcam -C configuration.xml (configuration.xml is a symlink to /opt/gcam-core-gcam-v7.0/exe/configuration_ref.xml for now), this is what happens:

```
$ ./gcam -C configuration.xml 
This computer software was prepared by Battelle Memorial Institute,
.
. _Scissors of brevity_
.
Running GCAM model code base version 7.0 revision gcam-v7.0

Configuration file:  configuration.xml
Parsing input files...
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "WildcardExpandingClassLoader"). To use archived non-system classes, this property must not be set
Error occurred during initialization of VM
java.lang.Error: WildcardExpandingClassLoader
        at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.6/ClassLoader.java:1995)
        at java.lang.System.initPhase3(java.base@17.0.6/System.java:2246)
Caused by: java.lang.ClassNotFoundException: WildcardExpandingClassLoader
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@17.0.6/BuiltinClassLoader.java:641)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@17.0.6/ClassLoaders.java:188)
        at java.lang.ClassLoader.loadClass(java.base@17.0.6/ClassLoader.java:520)
        at java.lang.Class.forName0(java.base@17.0.6/Native Method)
        at java.lang.Class.forName(java.base@17.0.6/Class.java:467)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.6/ClassLoader.java:1981)
        at java.lang.System.initPhase3(java.base@17.0.6/System.java:2246)
```
I did some grepping around and found that /opt/gcam-core-gcam-v7.0/cvs/objects/reporting/source/xml_db_outputter.cpp includes the line
```
options[ 1 ].optionString = const_cast<char*>( "-Djava.system.class.loader=WildcardExpandingClassLoader" );
```
so it looks like the java.system.class.loader property being complained about is getting set by GCAM. 

What to do about this? How would it be to get rid of JVM command line options being set in GCAM C++ source such as xml_db_outputter.cpp and rebuilding?

**Comment by MincingWords** [comment]
**UPDATE:** I tried backing down versions of JDK to see if it would change anything. Building with openjdk-bin-8 (1.8) hit this:
```
g++ -o gcam.exe -O3 -pthread -ggdb -DNDEBUG -DFUSION_MAX_VECTOR_SIZE=30  -MMD -std=c++17 -Wno-deprecated -Wl,-rpath,/etc/java-config-2/current-system-vm/lib/server -Wl,-rpath,/usr/lib64/  main.o -lgcam  -L/usr/local/lib -L/opt/gcam/cvs/objects/build/linux -L/etc/java-config-2/current-system-vm/lib/server -L/usr/lib64/ -ljvm -lhector -ltbb -ltbbmalloc -ltbbmalloc_proxy -lm 
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -ljvm: No such file or directory
```
Building with openjdk-bin-11 gives the same error as openjdk-bin-17 did but it doesn't issue the explanatory warning message:
```
.
.
.
Running GCAM model code base version 7.0 revision gcam-v7.0

Configuration file:  configuration.xml
Parsing input files...
Error occurred during initialization of VM
java.lang.Error: WildcardExpandingClassLoader
        at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.18/ClassLoader.java:1990)
        at java.lang.System.initPhase3(java.base@11.0.18/System.java:2074)
Caused by: java.lang.ClassNotFoundException: WildcardExpandingClassLoader
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.18/BuiltinClassLoader.java:581)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.18/ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(java.base@11.0.18/ClassLoader.java:522)
        at java.lang.Class.forName0(java.base@11.0.18/Native Method)
        at java.lang.Class.forName(java.base@11.0.18/Class.java:398)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.18/ClassLoader.java:1976)
        at java.lang.System.initPhase3(java.base@11.0.18/System.java:2074)
```

**Comment by MincingWords** [comment]
I got a successful build of gcam.exe under openjdk-bin-8 by adding a symlink named libjvm.so that points to /opt/openjdk-bin-8.362_p09/jre/lib/amd64/server/libjvm.so and I also changed the value of JARS_LIB to JARS_LIB=/opt/openjdk-bin-8.362_p09/jre/lib/amd64/server/*:/opt/gcam/exe/*.jar and changed JAVA_LIB to $JAVA_HOME/jre/lib/amd64/server/ (under these conditions, this is where openjdk-bin-8's  libjvm.so is located).

As a regular user I have a directory my_gcam with contents as follows:
```
lrwxrwxrwx 1 jeff jeff  50 Jun 22 22:32 configuration.xml -> /opt/gcam-core-gcam-v7.0/exe/configuration_ref.xml
lrwxrwxrwx 1 jeff jeff  22 Jun 22 22:34 gcam -> /opt/gcam/exe/gcam.exe
-rwxr-xr-x 1 jeff jeff 414 Jun 26 15:25 gcam_envs_setup.sh
lrwxrwxrwx 1 jeff jeff  41 Jun 22 22:37 log_conf.xml -> /opt/gcam-core-gcam-v7.0/exe/log_conf.xml
```
I cd to there before before proceeding. I next source gcam_envs_setup.sh; it looks like this now:
```
#/bin/bash
export CXX=g++
export BOOST_INCLUDE=/usr/include/boost/
export BOOST_LIB=/usr/lib64
export JARS_LIB=/opt/openjdk-bin-8.362_p09/jre/lib/amd64/server/*:/opt/gcam/exe/*.jar
# Note: /etc/java-config-2/current-system-vm/ is a symlink controlled by the system according to the most recent
# setting of system or user JVM
export JAVA_INCLUDE=/etc/java-config-2/current-system-vm/include
export JAVA_LIB=$JAVA_HOME/jre/lib/amd64/server/
export EIGEN_INCLUDE=/usr/include/eigen3
export TBB_INCLUDE=/usr/include/tbb
export TBB_LIB=/usr/lib64
```
And yet, with all this:
```
 ~/my_gcam $ **./gcam -C configuration.xml** 
./gcam: error while loading shared libraries: libjvm.so: cannot open shared object file: No such file or directory
```
I've tried putting a symlink for libjvm.so in ~/my_gcam and I still get the same error. I've tried adding its location to PATH and to LIB and still no joy. Where is the running gcam.exe expecting to find libjvm.so?

**Comment by MincingWords** [comment]
UPDATE: setting LD_LIBRARY_PATH to /opt/openjdk-bin-8/jre/lib/amd64/server solved the can't-find-liblvm.so problem only to hit the same java.lang.ClassNotFoundException error as hit originally. So I guess I'm back to asking about that:
```
Error occurred during initialization of VM
java.lang.Error: java.lang.ClassNotFoundException: WildcardExpandingClassLoader
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1462)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1429)
Caused by: java.lang.ClassNotFoundException: WildcardExpandingClassLoader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2202)
        at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2188)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1449)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1429)
```

**Comment by MincingWords** [comment]
I wasn't sure whether to start a new thread or not because prior to this posting I seem to have gone in a circle; I started with one problem (the title topic) and got past it only to wind up where I started.

I am also needing to put GCAM (7.0) on another machine, this time under MS Windows, so I downloaded that distribution without doing any sort of source building. This will be a multiuser install so I made changes to run-gcam.bat as needed, changing the values of JAVA_HOME and CLASSPATH like so:

```
SET JAVA_HOME=C:\Program Files\Java\jdk-17
SET CLASSPATH=C:\gcam-v7.0\libs\jars*;C:\gcam-v7.0\exe\XMLDBDriver.jar
```
I made myself a directory for running GCAM as a regular user and populated it like so:
```
06/28/2023  11:21 PM             9,446 configuration.xml
06/28/2023  11:21 PM             3,758 log_conf.xml
06/28/2023  11:19 PM    <JUNCTION>     run-gcam.bat [...]
```
And so I was all set. But:
```
Running GCAM model code base version 7.0 revision gcam-v7.0

Configuration file:  configuration.xml
Parsing input files...
Java HotSpot(TM) 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "WildcardExpandingClassLoader"). To use archived non-system classes, this property must not be set
Error occurred during initialization of VM
java.lang.Error: WildcardExpandingClassLoader
        at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.7/ClassLoader.java:1995)
        at java.lang.System.initPhase3(java.base@17.0.7/System.java:2246)
Caused by: java.lang.ClassNotFoundException: WildcardExpandingClassLoader
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@17.0.7/BuiltinClassLoader.java:641)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@17.0.7/ClassLoaders.java:188)
        at java.lang.ClassLoader.loadClass(java.base@17.0.7/ClassLoader.java:520)
        at java.lang.Class.forName0(java.base@17.0.7/Native Method)
        at java.lang.Class.forName(java.base@17.0.7/Class.java:467)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.7/ClassLoader.java:1981)
        at java.lang.System.initPhase3(java.base@17.0.7/System.java:2246)
```
**Exact same behavior I was getting from my local build under Gentoo Linux with Java 17.**

Am I the only person getting this warning and apparently related error? Again, I'll ask: are lines like this needed in the GCAM source code?
```
options[ 1 ].optionString = const_cast<char*>( "-Djava.system.class.loader=WildcardExpandingClassLoader" );
```

**Comment by pralitp** [comment]
The problem is not with your Java but rather:
> export JARS_LIB=/opt/openjdk-bin-17.0.6_p10/lib/*:/opt/gcam/exe/*.jar

A couple of things:
1. `/opt/gcam/exe/*.jar` This isn't actually the correct syntax for a Java class path.  If you want all jars in the exe folder it should read `/opt/gcam/exe/*` (Note, to be safe from your shell doing expansion of that star you should probably quote your entire `JARS_LIB='...'`)
2. The idea with this variable is to find all the third party libs that are needed to run the Model Interface.  I'm not sure if you happened to copy them to your exe directory.  Typically, we recommend keeping them in `libs/jars` but that isn't strictly necessary.  In case you do not already have them you can find them in one of the GCAM release packages (these are platform independent) or the `jars.zip` on the Model Interface Releases: https://github.com/JGCRI/modelinterface/releases

**Comment by pralitp** [comment]
Also, on Windows:
> SET CLASSPATH=C:\gcam-v7.0\libs\jars*;C:\gcam-v7.0\exe\XMLDBDriver.jar

This is similar.  It should be `C:\gcam-v7.0\libs\jars\*;C:\gcam-v7.0\exe\XMLDBDriver.jar` (Technically it should reference `C:\gcam-v7.0\output/modelinterface/ModelInterface.jar` too although you might be able to get by without it).

That being said.  If you download the Windows Release package you can get by without setting the `CLASSPATH` at all (you probably do want to set the `JAVA_HOME` however, if the default Java found on your system is not reliable).
