### ISSUE TITLE
ModelInterface throws error when opening database

### ISSUE THREAD

**Issue by publicmatt** [JGCRI/gcam-core#316]
```
❯ java -classpath "./output/modelinterface/jars/*:./output/modelinterface/ModelInterface.jar" ModelInterface.InterfaceMain
PROPERTY CHANGEtitle                                                                                 
PROPERTY CHANGEdocument-replaced                                                                                                                                                                           
DOCUMENT REPLACED                                                                                    
PROPERTY CHANGEdocument-replaced           
DOCUMENT REPLACED                                                                                    
Going to change controls                                                                                                                                                                                   
java.lang.NoSuchFieldError: CHOP                                                                                                                                                                           
        at ModelInterface.ModelGUI2.xmldb.XMLDB.openDB(XMLDB.java:188)                          
        at ModelInterface.ModelGUI2.xmldb.XMLDB.<init>(XMLDB.java:157)      
        at ModelInterface.ModelGUI2.xmldb.XMLDB.openDatabase(XMLDB.java:115)  
        at ModelInterface.ModelGUI2.DbViewer.doOpenDB(DbViewer.java:439)
        at ModelInterface.ModelGUI2.DbViewer.actionPerformed(DbViewer.java:363)
        [...]
```
I get the following error trying to open `database_basexdb` and `Main_queries.xml`:

```java.lang.NoSuchFieldError: CHOP```

![image](https://github.com/JGCRI/gcam-core/assets/52261150/82025d06-9ce9-4991-a774-b103aaeaf953)

At that point, the interface hangs and I have to force close it:

![image](https://github.com/JGCRI/gcam-core/assets/52261150/ff9dcd92-6937-4f72-adc7-c1476920c12a)

When I try to quit using the GUI, I get the following error:
```
Caught the window closing
java.lang.NullPointerException: Cannot invoke "ModelInterface.ModelGUI2.QueryTreeModel.hasChanges()" because "this.this$0.queries" is null
        at ModelInterface.ModelGUI2.DbViewer$1.propertyChange(DbViewer.java:195)
        at ModelInterface.InterfaceMain.fireProperty(InterfaceMain.java:494)
        at ModelInterface.InterfaceMain$3.windowClosing(InterfaceMain.java:378)
        [...]
```
![image](https://github.com/JGCRI/gcam-core/assets/52261150/d7e6df49-6e4e-4536-a093-49a642bfca6e)

**Comment by amnmalik** [comment]
Hi publicmatt, Not from the JGCRI team, but could be of help. Is this on mac os or windows? On windows check check if you have the right version (32 or 64) installed. On Windows, I also faced some errors with OpenJDK and when I replaced with Java from the Oracle website, it worked.

**Comment by publicmatt** [comment]
> Hi publicmatt, Not from the JGCRI team, but could be of help. Is this on mac os or windows? On windows check check if you have the right version (32 or 64) installed. On Windows, I also faced some errors with OpenJDK and when I replaced with Java from the Oracle website, it worked.

Thanks for the response - this was on Ubuntu 22.04.2 LTS. But it's definitely possible that it's a JDK issue.
